{************************************************}
{                                                }
{ Overlay Demo Unit                              }
{ Copyright (c) 1985,90 by Borland International }
{                                                }
{************************************************}

{$O+,F+}
unit OvrDemo1;
{ This unit is used by OVRDEMO.PAS }

interface

procedure Write1;

implementation

procedure Write1;
begin
  Writeln('One...');
end;

end.
