# -----------------------------------
# makefile by bill buckels 2008
# -----------------------------------
PRG=bsv2txt
$(PRG).exe: $(PRG).o
            ln -o $(PRG).com $(PRG).o c.lib
            del $(PRG).o
            @echo All Done!

$(PRG).o: $(PRG).c
           cc $(PRG).c
          