{************************************************}
{                                                }
{   Turbo Vision 2.0 Demo                        }
{   Copyright (c) 1992 by Borland International  }
{                                                }
{************************************************}

program Minimal;

uses App;

var
  MyApp: TApplication;

begin
  MyApp.Init;
  MyApp.Run;
  MyApp.Done;
end.
