{************************************************}
{                                                }
{   Turbo Vision 2.0 Demo                        }
{   Copyright (c) 1992 by Borland International  }
{                                                }
{************************************************}

unit TutConst; { Contains global constants for Turbo Vision Tutorial }

interface

const
  cmOrderNew = 251;
  cmOrderWin = 252;
  cmOrderSave = 253;
  cmOrderCancel = 254;
  cmOrderNext = 255;
  cmOrderPrev = 250;
  cmClipShow = 260;
  cmAbout = 270;
  cmFindOrderWindow = 2000;

const
  cmOptionsVideo = 1502;
  cmOptionsSave = 1503;
  cmOptionsLoad = 1504;

const
  cmStockNew = 241;
  cmStockWin = 242;
  cmStockSave = 243;
  cmStockCancel = 244;
  cmStockNext = 245;
  cmStockPrev = 240;

const
  cmSupplierNew = 231;
  cmSupplierWin = 232;
  cmSupplierSave = 233;
  cmSupplierCancel = 234;
  cmSupplierNext = 235;
  cmSupplierPrev = 230;

implementation

end.
