/* Copyright Manx Software Systems, Inc. 1987.  All rights reserved */

#ifndef __LIMITS
#define CHAR_BIT	8
#define SCHAR_MIN	-128
#define SCHAR_MAX	127
#define CHAR_MIN	-128
#define CHAR_MAX	127
#define UCHAR_MAX	255
#define SHRT_MIN	0x8000
#define SHRT_MAX	0x7fff
#define USHRT_MAX	0xffffU
#define INT_MIN		0x8000
#define INT_MAX		0x7fff
#define UINT_MAX	0xffffU
#define LONG_MIN	0x80000000L
#define LONG_MAX	0x7fffffffL
#define ULONG_MAX	0xffffffffU

#define __LIMITS
#endif
