SET COBDIR=C:\ntvdm\COBOL\BIN;
SET LIB=C:\ntvdm\COBOL\LIB;
SET INCLUDE=C:\ntvdm\COBOL\SOURCE;
SET HELPFILES=C:\ntvdm\COBOL\HELP;
SET INIT=C:\ntvdm\COBOL\INIT;
PATH C:\ntvdm\COBOL\BIN;
set TEMP=C:\TEMP


