{************************************************}
{                                                }
{   Turbo Vision Demo                            }
{   Copyright (c) 1990 by Borland International  }
{                                                }
{************************************************}

unit DemoCmds;

{$D-}

interface

const
  cmAbout           = 1002;
  cmPuzzle          = 1003;
  cmCalendar        = 1004;
  cmAsciiTab        = 1005;
  cmCalculator      = 1006;
  cmMouse           = 1007;
  cmColors          = 1008;
  cmSaveDesktop     = 1010;
  cmRetrieveDesktop = 1011;
  cmShowClip        = 1012;

implementation

end.
