unit DEMOHELP;

interface

const

  hcAsciiTable           = 6;
  hcCalculator           = 4;
  hcCalendar             = 5;
  hcCancelBtn            = 30;
  hcEdit                 = 14;
  hcFCChDirDBox          = 32;
  hcFile                 = 13;
  hcFind                 = 17;
  hcFOFileOpenDBox       = 26;
  hcFOFiles              = 28;
  hcFOName               = 27;
  hcFOOpenBtn            = 29;
  hcNoContext            = 0;
  hcOCColorsDBox         = 34;
  hcOColors              = 23;
  hcOMMouseDBox          = 33;
  hcOMouse               = 22;
  hcOpenBtn              = 31;
  hcOptions              = 21;
  hcORestoreDesktop      = 25;
  hcOSaveDesktop         = 24;
  hcPrevious             = 65318;
  hcPuzzle               = 3;
  hcReplace              = 18;
  hcSAbout               = 8;
  hcSAsciiTable          = 11;
  hcSCalculator          = 12;
  hcSCalendar            = 10;
  hcSearch               = 16;
  hcSearchAgain          = 19;
  hcShowClip             = 15;
  hcSPuzzle              = 9;
  hcSystem               = 7;
  hcViewer               = 2;
  hcWindows              = 20;

implementation

end.
