/*
 * DDS MICRO-C: Definitions for TSR function on IBM P.C.
 *
 * Copyright 1990-1994 Dave Dunfield
 * All rights reserved.
 */

/* HOT-KEY bit definitions */
#define	ALT		0x0008		/* Alt key */
#define	CONTROL	0x0004		/* Control key */
#define	L_SHIFT	0x0002		/* Left shift key */
#define	R_SHIFT	0x0001		/* Right shift key */
#define	SYS_REQ	0x0400		/* Alt-SysReq */

#define	SCR_BUF	4006		/* Size of screen save buffer */
