
{ Turbo Calc }
{ Copyright (c) 1989 by Borland International, Inc. }

program TCalc;
{ Turbo Pascal 5.5 object-oriented example main module.
  Object-oriented spreadsheet program.
  See TCALC.DOC for more information about this example.
}

{$S-}

uses TCRun;

begin   { Call main procedure.  The program is designed this way to make    }
  Run;  { compiles faster.  Since the main source file gets compiled every  }
end.    { every time, it makes sense to make the file as small as possible. }
