/*
 * limits.h
 *
 * contains defines for a number of implementation dependent values which are
 * commonly used in C programs.
 *
 * Copyright (C) Microsoft Corporation, 1985, 1986
 *
 */

#define SCHAR_MAX 127
#define SCHAR_MIN -127
#define UCHAR_MAX 255
#define CHAR_BIT 8
#define CHAR_MAX 127
#define CHAR_MIN 0
#define USHRT_MAX 0xffff
#define SHRT_MAX 32767
#define SHRT_MIN -32767
#define UINT_MAX 0xffff
#define ULONG_MAX 0xffffffff
#define INT_MAX 32767
#define INT_MIN -32767
#define LONG_MAX 2147483647
#define LONG_MIN -2147483647
#define LDBL_RADIX 2
#define LDBL_ROUNDS 0
#define LDBL_MAX_EXP 306
#define LDBL_MIN_EXP -306
#define LDBL_DIG 15
#define DBL_RADIX 2
#define DBL_ROUNDS 0
#define DBL_MAX_EXP 306
#define DBL_MIN_EXP -306
#define DBL_DIG 15
#define FLT_RADIX 2
#define FLT_ROUNDS 0
#define FLT_MAX_EXP 38
#define FLT_MIN_EXP -38
#define FLT_DIG 7
