unit demohelp;

interface

const

  hcAsciiTable           = 6;
  hcCalculator           = 4;
  hcCalendar             = 5;
  hcCancelBtn            = 35;
  hcFCChDirDBox          = 37;
  hcFChangeDir           = 15;
  hcFDosShell            = 16;
  hcFExit                = 17;
  hcFile                 = 13;
  hcFOFileOpenDBox       = 31;
  hcFOFiles              = 33;
  hcFOName               = 32;
  hcFOOpenBtn            = 34;
  hcFOpen                = 14;
  hcNoContext            = 0;
  hcOCColorsDBox         = 39;
  hcOColors              = 28;
  hcOMMouseDBox          = 38;
  hcOMouse               = 27;
  hcOpenBtn              = 36;
  hcOptions              = 26;
  hcORestoreDesktop      = 30;
  hcOSaveDesktop         = 29;
  hcPuzzle               = 3;
  hcSAbout               = 8;
  hcSAsciiTable          = 11;
  hcSCalculator          = 12;
  hcSCalendar            = 10;
  hcSPuzzle              = 9;
  hcSystem               = 7;
  hcViewer               = 2;
  hcWCascade             = 22;
  hcWClose               = 25;
  hcWindows              = 18;
  hcWNext                = 23;
  hcWPrevious            = 24;
  hcWSizeMove            = 19;
  hcWTile                = 21;
  hcWZoom                = 20;

implementation

end.
